### ISSUE TITLE
test failed on Windows 10

### ISSUE THREAD

**Issue by Demonium** [abap-openapi/abap-openapi-client#30]
Hi,
I'm getting an error when test it on windows OS 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! abap-openapi-client@1.0.0 integration_test: `rm -rf output_test && abap_transpile ./abap_transpile_test.json && node output_test/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the abap-openapi-client@1.0.0 integration_test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
see log below
[2021-05-28T07_46_47_233Z-debug.log](https://github.com/abap-openapi/abap-openapi-client/files/6559200/2021-05-28T07_46_47_233Z-debug.log)

Problem come from the rm command not recognized on windows

**Comment by larshp** [comment]
this was rmdir not working? see https://github.com/abap-openapi/abap-openapi-client/issues/31#issuecomment-850419939

**Comment by larshp** [comment]
@Demonium

**Comment by Demonium** [comment]
Hello Larshp,
By changing the script with rmdir work fine
