### ISSUE TITLE
zcl_oapi_main.clas.js doesn't exist

### ISSUE THREAD

**Issue by Demonium** [abap-openapi/abap-openapi-client#31]
Hi,
I'm getting an error when test it on windows OS 

Module not found: Error: Can't resolve '../../output/zcl_oapi_main.clas.js' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'
resolve '../../output/zcl_oapi_main.clas.js' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'
  using description file: C:\Users\Demonium\Projects\node\abap-openapi-client\web\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: C:\Users\Demonium\Projects\node\abap-openapi-client\package.json (relative path: ./output/zcl_oapi_main.clas.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Demonium\Projects\node\abap-openapi-client\output\zcl_oapi_main.clas.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Demonium\Projects\node\abap-openapi-client\output\zcl_oapi_main.clas.js.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\Demonium\Projects\node\abap-openapi-client\output\zcl_oapi_main.clas.js.js doesn't exist
      as directory
        C:\Users\Demonium\Projects\node\abap-openapi-client\output\zcl_oapi_main.clas.js doesn't exist

webpack 5.38.1 compiled with 1 error in 10547 ms
i ｢wdm｣: Failed to compile.

The problem comes when I went to web folder and run npm run dev command to start the web application

**Comment by larshp** [comment]
@Demonium thanks for the bug report, try again

I've updated everything to latest

**Comment by larshp** [comment]
whats the input and error message? did you do `npm install` in the root and playground?

**Comment by Demonium** [comment]
only on root folder and web folder

**Comment by larshp** [comment]
whats the input and error message?

**Comment by Demonium** [comment]
I have many issue...:
First on when I run at root folder "npm test" I'm getting the error below:
[2021-05-28T12_51_53_614Z-debug.log](https://github.com/abap-openapi/abap-openapi-client/files/6560932/2021-05-28T12_51_53_614Z-debug.log)


When I go to web folder and run npm run dev I'm getting the error below:
× ｢wdm｣: assets by path *.js 30.1 MiB
  assets by chunk 3.56 MiB (id hint: vendors) 29 assets
  50 assets
asset 80a4c25b73c1f97077ed2ea63fb85cae.ttf 69.3 KiB [emitted] [immutable] [from: node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf] (auxiliary name: app)
asset index.html 613 bytes [emitted]
runtime modules 112 KiB 54 modules
modules by path ./node_modules/ 23.1 MiB
  javascript modules 23 MiB 2251 modules
  json modules 13.6 KiB
    modules by path ./node_modules/browserify-sign/ 2.23 KiB
      ./node_modules/browserify-sign/browser/algorithms.json 2.07 KiB [built] [code generated]
      ./node_modules/browserify-sign/browser/curves.json 162 bytes [built] [code generated]
    4 modules
optional modules 120 bytes [optional] 8 modules
modules by path ./src/ 10.3 KiB
  ./src/index.js 8.17 KiB [built] [code generated]
  ./src/index.css 1.32 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js!./src/index.css 877 bytes [built] [code generated]
11 modules

ERROR in ./src/index.js 24:6-60
Module not found: Error: Can't resolve '../../output/cl_abap_char_utilities.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 25:6-54
Module not found: Error: Can't resolve '../../output/cl_abap_codepage.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 26:6-56
Module not found: Error: Can't resolve '../../output/cl_abap_conv_in_ce.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 27:6-57
Module not found: Error: Can't resolve '../../output/cl_abap_conv_out_ce.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 28:6-52
Module not found: Error: Can't resolve '../../output/cl_abap_format.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 29:6-50
Module not found: Error: Can't resolve '../../output/cl_abap_gzip.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 30:6-50
Module not found: Error: Can't resolve '../../output/cl_abap_hmac.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 31:6-53
Module not found: Error: Can't resolve '../../output/cl_abap_matcher.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 32:6-50
Module not found: Error: Can't resolve '../../output/cl_abap_math.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 33:6-52
Module not found: Error: Can't resolve '../../output/cl_abap_random.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 34:6-54
Module not found: Error: Can't resolve '../../output/cl_abap_refdescr.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 35:6-51
Module not found: Error: Can't resolve '../../output/cl_abap_regex.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 36:6-57
Module not found: Error: Can't resolve '../../output/cl_abap_structdescr.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 37:6-56
Module not found: Error: Can't resolve '../../output/cl_abap_tabledescr.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 38:6-51
Module not found: Error: Can't resolve '../../output/cl_abap_tstmp.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 39:6-55
Module not found: Error: Can't resolve '../../output/cl_abap_typedescr.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 40:6-57
Module not found: Error: Can't resolve '../../output/cl_abap_unit_assert.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 41:6-49
Module not found: Error: Can't resolve '../../output/cl_abap_zip.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 42:6-55
Module not found: Error: Can't resolve '../../output/cl_gdt_conversion.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 43:6-48
Module not found: Error: Can't resolve '../../output/cl_gui_cfw.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 44:6-54
Module not found: Error: Can't resolve '../../output/cl_gui_container.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 45:6-62
Module not found: Error: Can't resolve '../../output/cl_gui_frontend_services.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 46:6-52
Module not found: Error: Can't resolve '../../output/cl_http_client.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 47:6-53
Module not found: Error: Can't resolve '../../output/cl_http_utility.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 48:6-45
Module not found: Error: Can't resolve '../../output/cl_ixml.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 49:6-59
Module not found: Error: Can't resolve '../../output/cl_sxml_string_reader.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 50:6-52
Module not found: Error: Can't resolve '../../output/cl_system_uuid.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 51:6-60
Module not found: Error: Can't resolve '../../output/cx_abap_message_digest.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 52:6-54
Module not found: Error: Can't resolve '../../output/cx_dynamic_check.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 53:6-64
Module not found: Error: Can't resolve '../../output/cx_parameter_invalid_range.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 54:6-63
Module not found: Error: Can't resolve '../../output/cx_parameter_invalid_type.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 55:6-45
Module not found: Error: Can't resolve '../../output/cx_root.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 56:6-53
Module not found: Error: Can't resolve '../../output/cx_static_check.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 57:6-51
Module not found: Error: Can't resolve '../../output/cx_sxml_error.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 58:6-67
Module not found: Error: Can't resolve '../../output/cx_sy_codepage_converter_init.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 59:6-63
Module not found: Error: Can't resolve '../../output/cx_sy_conversion_codepage.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 60:6-64
Module not found: Error: Can't resolve '../../output/cx_sy_conversion_no_number.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 61:6-61
Module not found: Error: Can't resolve '../../output/cx_sy_create_data_error.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 62:6-63
Module not found: Error: Can't resolve '../../output/cx_sy_create_object_error.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 63:6-58
Module not found: Error: Can't resolve '../../output/cx_sy_dyn_call_error.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 64:6-66
Module not found: Error: Can't resolve '../../output/cx_sy_dyn_call_illegal_class.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 65:6-67
Module not found: Error: Can't resolve '../../output/cx_sy_dyn_call_illegal_method.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 66:6-59
Module not found: Error: Can't resolve '../../output/cx_sy_move_cast_error.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 67:6-58
Module not found: Error: Can't resolve '../../output/cx_sy_ref_is_initial.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 68:6-52
Module not found: Error: Can't resolve '../../output/if_http_client.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 69:6-53
Module not found: Error: Can't resolve '../../output/if_http_request.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 70:6-54
Module not found: Error: Can't resolve '../../output/if_http_response.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 71:6-45
Module not found: Error: Can't resolve '../../output/if_ixml.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 72:6-55
Module not found: Error: Can't resolve '../../output/if_ixml_attribute.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 73:6-54
Module not found: Error: Can't resolve '../../output/if_ixml_document.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 74:6-53
Module not found: Error: Can't resolve '../../output/if_ixml_element.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 75:6-53
Module not found: Error: Can't resolve '../../output/if_ixml_istream.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 76:6-60
Module not found: Error: Can't resolve '../../output/if_ixml_named_node_map.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 77:6-50
Module not found: Error: Can't resolve '../../output/if_ixml_node.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 78:6-59
Module not found: Error: Can't resolve '../../output/if_ixml_node_iterator.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 79:6-55
Module not found: Error: Can't resolve '../../output/if_ixml_node_list.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 80:6-53
Module not found: Error: Can't resolve '../../output/if_ixml_ostream.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 81:6-52
Module not found: Error: Can't resolve '../../output/if_ixml_parser.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 82:6-54
Module not found: Error: Can't resolve '../../output/if_ixml_renderer.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 83:6-60
Module not found: Error: Can't resolve '../../output/if_ixml_stream_factory.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 84:6-48
Module not found: Error: Can't resolve '../../output/if_message.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 85:6-55
Module not found: Error: Can't resolve '../../output/if_sxml_attribute.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 86:6-59
Module not found: Error: Can't resolve '../../output/if_sxml_close_element.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 87:6-50
Module not found: Error: Can't resolve '../../output/if_sxml_node.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 88:6-58
Module not found: Error: Can't resolve '../../output/if_sxml_open_element.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 89:6-52
Module not found: Error: Can't resolve '../../output/if_sxml_reader.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 90:6-51
Module not found: Error: Can't resolve '../../output/if_sxml_value.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 91:6-56
Module not found: Error: Can't resolve '../../output/if_sxml_value_node.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 92:6-53
Module not found: Error: Can't resolve '../../output/if_t100_message.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 93:6-73
Module not found: Error: Can't resolve '../../output/openabap.fugr.convert_itf_to_stream_text.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 94:6-55
Module not found: Error: Can't resolve '../../output/openabap.fugr.docu_get.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 95:6-63
Module not found: Error: Can't resolve '../../output/openabap.fugr.system_callstack.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 96:6-57
Module not found: Error: Can't resolve '../../output/openabap.fugr.text_split.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 97:6-56
Module not found: Error: Can't resolve '../../output/zcl_oapi_abap_name.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 98:6-51
Module not found: Error: Can't resolve '../../output/zcl_oapi_json.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 99:6-51
Module not found: Error: Can't resolve '../../output/zcl_oapi_main.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 100:6-53
Module not found: Error: Can't resolve '../../output/zcl_oapi_parser.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 101:6-57
Module not found: Error: Can't resolve '../../output/zcl_oapi_references.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 102:6-53
Module not found: Error: Can't resolve '../../output/zcl_oapi_schema.clas.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 103:6-53
Module not found: Error: Can't resolve '../../output/zif_oapi_schema.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

ERROR in ./src/index.js 104:6-63
Module not found: Error: Can't resolve '../../output/zif_oapi_specification_v3.intf.mjs' in 'C:\Users\Demonium\Projects\node\abap-openapi-client\web\src'

81 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.38.1 compiled with 81 errors in 12143 ms
i ｢wdm｣: Failed to compile.


Does it help?

**Comment by larshp** [comment]
probably `rmdir` that is failing, try adjusting the script

**Comment by Demonium** [comment]
Much more easier: I have created the output folder at root and it's worked!!!!!!

**Comment by Demonium** [comment]
thanks for your help
